<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-04-18T12:54:35 CLT" name="Default suite" finished-at="2021-04-18T12:54:44 CLT" duration-ms="9356">
    <groups>
    </groups>
    <test started-at="2021-04-18T12:54:35 CLT" name="Default test" finished-at="2021-04-18T12:54:44 CLT" duration-ms="9356">
      <class name="pruebas.Laboratorio4">
        <test-method is-config="true" signature="setUp()[pri:0, instance:pruebas.Laboratorio4@71def8f8]" started-at="2021-04-18T12:54:32 CLT" name="setUp" finished-at="2021-04-18T12:54:35 CLT" duration-ms="2691" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="irURL()[pri:0, instance:pruebas.Laboratorio4@71def8f8]" started-at="2021-04-18T12:54:35 CLT" name="irURL" finished-at="2021-04-18T12:54:44 CLT" duration-ms="8734" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- irURL -->
        <test-method is-config="true" signature="maxVentana()[pri:0, instance:pruebas.Laboratorio4@71def8f8]" started-at="2021-04-18T12:54:44 CLT" name="maxVentana" finished-at="2021-04-18T12:54:44 CLT" duration-ms="196" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- maxVentana -->
        <test-method signature="login(java.lang.String, java.lang.String)[pri:0, instance:pruebas.Laboratorio4@71def8f8]" started-at="2021-04-18T12:54:44 CLT" name="login" data-provider="Datos para funcionalidad Login" finished-at="2021-04-18T12:54:44 CLT" duration-ms="0" status="FAIL">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Method public void pruebas.Laboratorio4.login(java.lang.String,java.lang.String) throws java.io.IOException requires a @DataProvider named : Datos para funcionalidad Login]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Method public void pruebas.Laboratorio4.login(java.lang.String,java.lang.String) throws java.io.IOException requires a @DataProvider named : Datos para funcionalidad Login
at org.testng.internal.Parameters.findDataProvider(Parameters.java:559)
at org.testng.internal.Parameters.handleParameters(Parameters.java:772)
at org.testng.internal.Parameters.handleParameters(Parameters.java:740)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:59)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:38)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:789)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="finPrueba()[pri:0, instance:pruebas.Laboratorio4@71def8f8]" started-at="2021-04-18T12:54:44 CLT" name="finPrueba" finished-at="2021-04-18T12:54:44 CLT" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- finPrueba -->
        <test-method is-config="true" signature="cierreNavegador()[pri:0, instance:pruebas.Laboratorio4@71def8f8]" started-at="2021-04-18T12:54:44 CLT" name="cierreNavegador" finished-at="2021-04-18T12:54:44 CLT" duration-ms="370" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cierreNavegador -->
        <test-method is-config="true" signature="finSuite()[pri:0, instance:pruebas.Laboratorio4@71def8f8]" started-at="2021-04-18T12:54:44 CLT" name="finSuite" finished-at="2021-04-18T12:54:44 CLT" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- finSuite -->
      </class> <!-- pruebas.Laboratorio4 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
